### ISSUE TITLE
SpriteBatch to actually handle batch rendering

### ISSUE THREAD

**Issue by maciejhirsz** [not-fl3/good-web-game#12]
Now that #10 got merged, it would make sense to actually batch the renders from it, as good-web-game is doubly penalized for not using it (once for having to access GPU per every sprite, twice by having to do that by whatever magical JS bindings stdweb provides).

I can tackle this, but not immediately.

**Comment by not-fl3** [comment]
It was quite a long way to get here, but finally fixed with https://github.com/not-fl3/good-web-game/commit/b7c47166b5892a72b72b3b317b173f2ac7de8a62

Example code: https://github.com/not-fl3/good-web-game/blob/master/examples/spritebatch.rs

[online demo](https://not-fl3.github.io/miniquad-samples/spritebatch.html)
