### ISSUE TITLE
GC Image's Texture somehow?

### ISSUE THREAD

**Issue by maciejhirsz** [not-fl3/good-web-game#14]
It doesn't look like we call `gl_ctx.delete_texture` anywhere if the `Image` is dropped? It might be nice to add if some images are created and dropped, maybe use an `Rc` or some such on the `Texture`? Either way, I don't think it's a high priority right now.

**Comment by PSteinhaus** [comment]
Hah, just realized that this problem still remains, too bad. Also it's not only a question with images, but also with meshes, as these can also have textures.

The problem really lies in when to delete the `Texture`. So wrapping it an `Rc` and then another wrapper type for which we can then implement `Drop` as `self.texture.delete()` seems sensible.

**Comment by PSteinhaus** [comment]
fixed in #55 by splitting the `Arc` called `clone_hack` into `texture_clone_hack` and `bindings_clone_hack`, allowing `Image`s to delete their buffers (but not their texture) on being dropped, as soon as the last clone of this `Image` is dropped.

Their texture is deleted when the last entity holding a clone of `texture_clone_hack` is dropped (which can also be a `Mesh`).
